# Generated by Django 5.0.4 on 2025-02-20 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0003_wordpair"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en", models.CharField(max_length=255)),
                ("ru", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        related_query_name="sentence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        related_name="sentences",
                        related_query_name="sentence",
                        to="vocabulary.wordpair",
                    ),
                ),
            ],
        ),
    ]
