# Generated by Django 5.0.4 on 2025-02-20 12:14

from django.db import migrations, models


def create_english_levels(apps, schema_editor):
    EnglishLevel = apps.get_model('vocabulary', 'EnglishLevel')
    EnglishLevel.objects.bulk_create([
        EnglishLevel(id='A0', name='Beginner', start=1, end=500),
        EnglishLevel(id='A1', name='Elementary', start=501, end=1000),
        EnglishLevel(id='A2', name='Pre Intermediate', start=1001, end=2000),
        EnglishLevel(id='B1', name='Intermediate', start=2001, end=3500),
        EnglishLevel(id='B2', name='Upper Intermediate', start=3501, end=5000),
        EnglishLevel(id='C1', name='Advanced', start=5001, end=8000),
        EnglishLevel(id='C2', name='Proficient', start=8001, end=20000),
    ])

def delete_english_levels(apps, schema_editor):
    EnglishLevel = apps.get_model('vocabulary', 'EnglishLevel')
    EnglishLevel.objects.all().delete()



class Migration(migrations.Migration):

    initial = True
    atomic = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnglishLevel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
            ],
        ),
        migrations.RunPython(create_english_levels, delete_english_levels),
    ]
