# Generated by Django 5.0.4 on 2025-02-20 18:35

from django.db import migrations, models
import csv


def create_default_words(apps, schema_editor):
    DefaultWord = apps.get_model('vocabulary', 'DefaultWord')
    words_to_create = []
    with open('_data/clean.csv') as csv_file:
        reader = csv.reader(csv_file)
        for number_in_dict, en, ru in reader:
            default_word = DefaultWord(
                number_in_dict=number_in_dict,
                ru=ru,
                en=en,
            )
            words_to_create.append(default_word)
    DefaultWord.objects.bulk_create(words_to_create)


def delete_default_words(apps, schema_editor):
    DefaultWord = apps.get_model('vocabulary', 'DefaultWord')
    DefaultWord.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_in_dict", models.PositiveIntegerField()),
                ("en", models.CharField(max_length=100)),
                ("ru", models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(create_default_words, delete_default_words),
    ]
